version: "3.6"

services:
  mysql:
    image: mysql:5.7
    secrets:
      - mysql_root_passwd
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_passwd
    ports:
      - "3306:3306"

secrets:
  mysql_root_passwd:
    external: true
