ARG centos_version=7
FROM centos:$centos_version
# needed to do again after FROM due to docker limitation
ARG centos_version

WORKDIR /var/code
COPY ./build_program.sh .
COPY ./install_ohmyzsh.sh .

RUN locale
RUN localedef -i zh_CN -c -f UTF-8 zh_CN.UTF-8
RUN echo "export LC_ALL=zh_CN.UTF-8" >> /etc/profile && source /etc/profile
ENV LANG zh_CN.UTF-8
ENV LC_CTYPE zh_CN.UTF-8

RUN yum install -y git  \
    subversion \
    gcc \
    cmake \
    gcc-c++ \
    make \
    python3 \
    python3-devel \
    java-1.8.0-openjdk-devel \
    maven \
    zsh \
    && chmod +x ./build_program.sh \
    && chmod +x ./install_ohmyzsh.sh
