version: "3"

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8081"
      - "8085:8085"
    volumes:
      - nexus-data:/nexus-data

volumes:
  nexus-data:

